### ISSUE TITLE
how do you install/import to xcode to make an ipa file for iphone for supertux?

### ISSUE THREAD

**Issue by jerlegoman** [SuperTuxTeam/downloads#2]
how do you install/import to xcode to make an ipa file for iphone for supertux?

**Comment by maxteufel** [comment]
iOS and Android are currently not supported. At this moment, there are no plans to add support for these platforms in the near future. If you want to contribute by porting the game to iOS, you can find the source code at [SuperTux/supertux](https://github.com/SuperTux/supertux). The source code includes files for CMake, which allows generating Xcode projects. However, be aware that these Xcode projects are intended for compiling on and for OS X, so if you want to build a mobile app, prepare to fix several issues, eventually even requiring to port the renderer.

**Comment by jerlegoman** [comment]
Yes but there is an iPhone zip file in the others folder.

**Comment by maxteufel** [comment]
That is an outdated (5 years old), unofficial, and unsupported codebase that is only there for archival purposes. I guess you'd just cross-compile all the files into a binary, and manually package & sign the IPA.
